language: elixir

elixir:
  - '1.6.4'

otp_release: '20'

matrix:
  fast_finish: true
    #   include:
    #       - elixir: '1.3'
    #         otp_release: '19'

script:
  - mix deps.get
  - mix test
  - mix coveralls

notifications:
  recipients:
    - celaxodon@gmail.com
