language: elixir

elixir:
  - 1.6.4

otp_release:
  - 20.2

matrix:
  fast_finish: true
    #   include:
    #       - elixir: '1.3'
    #         otp_release: '19'

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix clean
  - mix test

after_script:
  - mix coveralls.travis
  - mix coveralls.post

notifications:
  recipients:
    - celaxodon@gmail.com
