language: elixir

elixir:
  - 1.6.4

otp_release:
  - 20.2

matrix:
  fast_finish: true
    #   include:
    #       - elixir: '1.3'
    #         otp_release: '19'

# before_install:
#   - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
#   - sudo dpkg -i erlang-solutions_1.0_all.deb
#   - sudo apt-get update
#   - sudo apt-get install esl-erlang
#   - sudo apt-get install elixir

env:
  matrix:
    - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix clean
  - mix test

after_script:
  - mix coveralls.travis

cache:
  directories:
    - _build
    - deps

notifications:
  recipients:
    - celaxodon@gmail.com
